language: python
cache: pip
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
branches:
  only:
    - aru-test
    - /v(\d+\.){2}\d+(-rc\.\d+)?/ # regex for tag branches e.g. v0.22.0-rc.1, v0.22.0 etc
notifications:
  recipients:
    - hello@isala.me
  email:
    on_success: change
    on_failure: always

before_install:
  # Loop until update succeeds (timeouts can occur)
  - sudo sed -e '/postgresql/ s/^#*/#/' -i /etc/apt/sources.list.d/*
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo add-apt-repository ppa:longsleep/golang-backports -y
  # workaround for https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  # Loop until update succeeds (timeouts can occur)
  - travis_retry $(! sudo apt-get -qq update 2>&1 | grep Failed)
  - sudo apt-get install -y g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install -y gnupg2 git
  - sudo apt-get install -y golang-1.12
  - export PATH="/usr/lib/go-1.12/bin:$PATH"
  - export GOROOT=/usr/lib/go-1.12
  - go version

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage black

script:
  - make build_helm_binding
  - make test && make test_coverage && make test_formatting
  - make build_binary
  - make test_binary

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./scripts/inc_version.sh; fi

before_deploy:
  - export PRERELEASE=false
  # - if $(echo $TRAVIS_BRANCH | grep -Eq "v([0-9]+.[0-9]{2}.[0-9]+)-rc.[0-9]+"); then export PRERELEASE=true; fi
  # - echo "Deploying $TRAVIS_BRANCH, prerelease $PRERELEASE"
  - git submodule update --init --recursive
deploy:
  - provider: releases
    api_key: $GITHUB_AUTHKEY
    file:
      - CHANGELOG.md
      - bindist/kapitan-linux-amd64
    prerelease: false
    on:
      tags: true
      repo: mrsupiri/kapitan
after_deploy:
  - bash ./scripts/after_deploy.sh
